AFTERSALE_STATUS_PENDING_PURCHASE = '待采购'
AFTERSALE_STATUS_PENDING_FOLLOW_UP = '待跟进'
AFTERSALE_STATUS_PURCHASED_PENDING_INBOUND = '已采购待入库'
AFTERSALE_STATUS_ONSITE_SERVICE = '上门售后'
AFTERSALE_STATUS_COMPLETED = 'Completed'

AFTERSALE_STATUS = [
	(AFTERSALE_STATUS_PENDING_PURCHASE, AFTERSALE_STATUS_PENDING_PURCHASE),
	(AFTERSALE_STATUS_PENDING_FOLLOW_UP, AFTERSALE_STATUS_PENDING_FOLLOW_UP),
	(AFTERSALE_STATUS_PURCHASED_PENDING_INBOUND, AFTERSALE_STATUS_PURCHASED_PENDING_INBOUND),
	(AFTERSALE_STATUS_ONSITE_SERVICE, AFTERSALE_STATUS_ONSITE_SERVICE),
	(AFTERSALE_STATUS_COMPLETED, AFTERSALE_STATUS_COMPLETED),
]

AFTERSALE_ISSUE_CATEGORY = [
	('厂家问题', '厂家问题'),
	('送货问题', '送货问题'),
	('质量问题', '质量问题'),
	('客人问题', '客人问题'),
	('仓库问题', '仓库问题'),
	('ALLIED', 'ALLIED'),
	('购买', '购买'),
	('未知', '未知'),
]

DELIVERY_INFO_OPTIONS = [
	('-', '-'),
	('ALLIED', 'ALLIED'),
	('BNE 第三方送货', 'BNE 第三方送货'),
	('BNE 第三方ALLIED', 'BNE 第三方ALLIED'),
	('MEL 第三方送货', 'MEL 第三方送货'),
	('MEL 第三方ALLIED', 'MEL 第三方ALLIED'),
]
