REFUND_STATUS_NEW = 'New'
REFUND_STATUS_WIP = 'WIP'
REFUND_STATUS_COMPLETED = 'Completed'
REFUND_STATUS_CANCELLED = 'Cancelled'

REFUND_STATUS = [
	(REFUND_STATUS_NEW, 'New'),
	(REFUND_STATUS_WIP, 'WIP'),
	(REFUND_STATUS_COMPLETED, 'Completed'),
	(REFUND_STATUS_CANCELLED, 'Cancelled'),
]

REFUND_ALLOWED_TRANSITIONS = {
	REFUND_STATUS_NEW: [REFUND_STATUS_WIP, REFUND_STATUS_CANCELLED],
	REFUND_STATUS_WIP: [REFUND_STATUS_COMPLETED, REFUND_STATUS_CANCELLED],
	REFUND_STATUS_COMPLETED: [],
	REFUND_STATUS_CANCELLED: [],
}
